dockerhub: &dockerhub
  auto_tag: true
  group: platform
  image: plugins/docker
  secrets:
    - docker_username
    - docker_password
  when:
    branch:
      - develop
      - master

rancher: &rancher
  image: peloton/drone-rancher
  confirm: true
  secrets:
    - source: rancher_access_key
      target: plugin_access_key
    - source: rancher_secret_key
      target: plugin_secret_key
  timeout: 120
  url: https://master.nativecode.com

slack: &slack
  image: plugins/slack
  channel: builds
  username: drone
  secrets:
    - source: webhook_slack_builds
      target: plugin_webhook

pipeline:
  build:
    image: microsoft/dotnet:sdk
    commands:
      - curl --silent --location https://deb.nodesource.com/setup_8.x | bash -
      - apt-get install nodejs -y
      - mkdir tools
      - cp templates/tools-csproj.template tools/tools.csproj
      - dotnet add tools/tools.csproj package Cake.CoreCLR -v $CAKE_VERSION --package-directory tools/Cake.CoreCLR.$CAKE_VERSION
      - dotnet tools/Cake.CoreCLR.$CAKE_VERSION/cake.coreclr/$CAKE_VERSION/Cake.dll build.cake -target="Default" -configuration="Release"
    environment:
      - CAKE_VERSION=0.30.0

  publish_identity:
    <<: *dockerhub
    repo: nativecode/platform-identity
    target: identity

  publish_node:
    <<: *dockerhub
    repo: nativecode/platform-node
    target: node

  publish_delegate:
    <<: *dockerhub
    repo: nativecode/platform-node-delegate
    target: delegate

  publish_processor:
    <<: *dockerhub
    repo: nativecode/platform-node-processor
    target: processor

  publish_watcher:
    <<: *dockerhub
    repo: nativecode/platform-node-watcher
    target: watcher

  release_identity:
    <<: *rancher
    docker_image: "nativecode/platform-identity:${DRONE_BRANCH}"
    service: "platform/identity"
    when:
      branch: master

  release_node:
    <<: *rancher
    docker_image: "nativecode/platform-node:${DRONE_BRANCH}"
    service: "platform/node"
    when:
      branch: master

  release_processor:
    <<: *rancher
    docker_image: "nativecode/platform-node-processor:${DRONE_BRANCH}"
    service: "platform/node-processor"
    when:
      branch: master

  release_watcher:
    <<: *rancher
    docker_image: "nativecode/platform-node-watcher:${DRONE_BRANCH}"
    service: "platform/node-watcher"
    when:
      branch: master

  notification:
    <<: *slack
    when:
      status: [success, failure]
