hub: &hub
  image: plugins/docker
  secrets: [ docker_username, docker_password ]

prod: &prod
  <<: *hub
  tags: [ "latest", "1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}" ]
  when:
    branch: [ master ]

deploy: &deploy
  image: peloton/drone-rancher
  confirm: true
  secrets:
    - source: rancher_access_key
      target: plugin_access_key
    - source: rancher_secret_key
      target: plugin_secret_key
  timeout: 120
  url: https://rancher.nativecode.net

deploy-internal: &deploy-internal
  image: peloton/drone-rancher
  confirm: true
  secrets:
    - source: rancher_internal_access_key
      target: plugin_access_key
    - source: rancher_internal_secret_key
      target: plugin_secret_key
  timeout: 120
  url: http://in.nativecode.com:8080

slack: &slack
  image: plugins/slack
  channel: builds
  username: drone
  secrets:
    - source: webhook_slack_builds
      target: plugin_webhook

pipeline:
  idp: &idp
    <<: *prod
    dockerfile: src/identity/Dockerfile
    repo: nativecode/identity

  node: &node
    <<: *prod
    dockerfile: src/node/Dockerfile
    repo: nativecode/media

  processor: &processor
    <<: *prod
    dockerfile: src/node-processor/Dockerfile
    repo: nativecode/media-processor

  watcher: &watcher
    <<: *prod
    dockerfile: src/node-watcher/Dockerfile
    repo: nativecode/media-watcher

  release-idp: &release-idp
    <<: *deploy
    docker_image: "nativecode/identity:1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}"
    service: "prod-identity/api"
    when:
      branch: master

  release-node: &release-node
    <<: *deploy
    docker_image: "nativecode/media:1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}"
    service: "prod-media/api"
    when:
      branch: master

  release-processor: &release-processor
    <<: *deploy-internal
    docker_image: "nativecode/media-processor:1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}"
    service: "platform/processor"
    when:
      branch: master

  release-watcher: &release-watcher
    <<: *deploy
    docker_image: "nativecode/media-watcher:1.0-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}"
    service: "prod-media/watcher"
    when:
      branch: master

  notification: &notification
    <<: *slack
    when:
      status: [ success, failure ]
