dockerhub: &dockerhub
  dockerfile: Dockerfile
  image: plugins/docker
  secrets: [docker_username, docker_password]

rancher: &rancher
  image: peloton/drone-rancher
  confirm: true
  secrets:
    - source: rancher_access_key
      target: plugin_access_key
    - source: rancher_secret_key
      target: plugin_secret_key
  timeout: 120
  url: https://master.nativecode.com

slack: &slack
  image: plugins/slack
  channel: builds
  username: drone
  secrets:
    - source: webhook_slack_builds
      target: plugin_webhook

pipeline:
  artifacts: &artifacts
    <<: *dockerhub
    repo: nativecode/platform-artifacts
    tags: ["artifacts-${DRONE_BRANCH}"]
    target: artifacts

  identity: &identity
    <<: *dockerhub
    repo: nativecode/platform-identity
    tags: ["latest", "${DRONE_BRANCH}"]
    target: identity
    when:
      branch: [develop, master]
  node: &node
    <<: *dockerhub
    repo: nativecode/platform-node
    tags: ["latest", "${DRONE_BRANCH}"]
    target: node
    when:
      branch: [develop, master]
  node-delegate: &node-delegae
    <<: *dockerhub
    repo: nativecode/platform-node-delegate
    tags: ["latest", "${DRONE_BRANCH}"]
    target: delegate
    when:
      branch: [develop, master]
  node-processor: &node-processor
    <<: *dockerhub
    repo: nativecode/platform-node-processor
    tags: ["latest", "${DRONE_BRANCH}"]
    target: processor
    when:
      branch: [develop, master]
  node-watcher: &node-watcher
    <<: *dockerhub
    repo: nativecode/platform-node-watcher
    tags: ["latest", "${DRONE_BRANCH}"]
    target: watcher
    when:
      branch: [develop, master]

  release-identity: &release-identity
    <<: *rancher
    docker_image: "nativecode/platform-identity:${DRONE_BRANCH}"
    service: "platform/identity"
    when:
      branch: master
  release-node: &release-node
    <<: *rancher
    docker_image: "nativecode/platform-node:${DRONE_BRANCH}"
    service: "platform/node"
    when:
      branch: master
  release-processor: &release-processor
    <<: *rancher
    docker_image: "nativecode/platform-node-processor:${DRONE_BRANCH}"
    service: "platform/node-processor"
    when:
      branch: master
  release-watcher: &release-watcher
    <<: *rancher
    docker_image: "nativecode/platform-node-watcher:${DRONE_BRANCH}"
    service: "platform/node-watcher"
    when:
      branch: master

  notification: &notification
    <<: *slack
    when:
      status: [success, failure]
