stages:
  - build

build:
  image: microsoft/dotnet:sdk
  stage: build
  script:
    - curl --silent --location https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install nodejs -y
    - mkdir tools
    - cp templates/tools-csproj.template tools/tools.csproj
    - dotnet add tools/tools.csproj package Cake.CoreCLR -v $CAKE_VERSION --package-directory tools/Cake.CoreCLR.$CAKE_VERSION
    - dotnet tools/Cake.CoreCLR.$CAKE_VERSION/cake.coreclr/$CAKE_VERSION/Cake.dll build.cake -target="Default" -configuration="Release"
